AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for a Java 21 application built as a Docker container

Resources:
  KrenzeeProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - arm64
      # Required for CodeDeploy traffic shifting
#      AutoPublishAlias: live 
#      DeploymentPreference:
#        Type: AllAtOnce 
      MemorySize: 1024
      Timeout: 30
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
